#
# Copyright (c) 2018 SUSE
#
# SPDX-License-Identifier: Apache-2.0

ARG IMAGE_REGISTRY=docker.io
# NOTE: OS_VERSION is set according to config.sh
FROM ${IMAGE_REGISTRY}/debian:@OS_VERSION@
@SET_PROXY@

ENV GO_HOME="/opt"
ENV GOCACHE="${GO_HOME}/.cache"
ENV RUSTUP_HOME="/opt/rustup"
ENV CARGO_HOME="/opt/cargo"
ENV PATH="/opt/cargo/bin/:/opt/go/bin:${PATH}"

ARG GO_VERSION
ARG RUST_TOOLCHAIN
ENV GO_HOME="/opt"
ENV PATH="/opt/go/bin:${PATH}"

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# RUN commands
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get --no-install-recommends install -y \
    apt-utils \
    autoconf \
    automake \
    binutils \
    build-essential \
    ca-certificates \
    chrony \
    coreutils \
    curl \
    debianutils \
    debootstrap \
    g++ \
    gcc \
    git \
    libc-dev \
    m4 \
    make \
    musl-tools \
    musl-dev \
    makedev \
    sed \
    systemd \
    tar \
    vim \
    wget \
    xz-utils \
    python3-full && \
    apt-get clean && rm -rf /var/lib/apt/lists/&& \
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain ${RUST_TOOLCHAIN}

RUN ARCH=$(uname -m); \
    goarch=""; \
    kernelname=$(uname -s | tr '[:upper:]' '[:lower:]'); \
    case "${ARCH}" in \
    "aarch64") goarch="arm64" ;; \
    "ppc64le") goarch=${ARCH} ;; \
    "x86_64") goarch="amd64" ;; \
    "s390x") goarch=${ARCH} ;; \
    *) echo "Unsupported architecture: ${ARCH}" && exit 1 ;; \
    esac; \
    curl -OL "https://storage.googleapis.com/golang/go${GO_VERSION}.${kernelname}-${goarch}.tar.gz" && \
    tar -C "${GO_HOME}" -xzf "go${GO_VERSION}.${kernelname}-${goarch}.tar.gz" && \
    rm "go${GO_VERSION}.${kernelname}-${goarch}.tar.gz"

# aarch64 requires this name -- link for all
RUN if [ ! -f "/usr/bin/$(uname -m)-linux-musl-gcc" ]; then ln -s /usr/bin/musl-gcc "/usr/bin/$(uname -m)-linux-musl-gcc"; fi

RUN ARCH=$(uname -m); \
    rust_arch=""; \
    libc=""; \
    case "${ARCH}" in \
    "aarch64") rust_arch="${ARCH}"; libc="musl"; ;; \
    "ppc64le") rust_arch="powerpc64le"; libc="gnu"; ;; \
    "x86_64") rust_arch="${ARCH}"; libc="musl"; ;; \
    "s390x") rust_arch="${ARCH}"; libc="gnu"; ;; \
    *) echo "Unsupported architecture: ${ARCH}" && exit 1 ;; \
    esac; \
    rustup target add "${rust_arch}-unknown-linux-${libc}"